"""empty message

Revision ID: 32244cf89de5
Revises: 1c29f1271d48
Create Date: 2023-08-18 09:32:33.282615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32244cf89de5'
down_revision = '1c29f1271d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='person_pkey'),
    sa.UniqueConstraint('email', name='person_email_key'),
    sa.UniqueConstraint('username', name='person_username_key')
    )
    op.drop_table('people')
    # ### end Alembic commands ###
